#!/usr/bin/env bash

## Config
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )" 
URL="https://github.com/gemmadlou/semantiq.git"
RELEASE=`semantiq release`
VERSION=`semantiq version`

cat > ~/.git-credentials <<EOL
https://gemmadlou:${GH_TOKEN}@github.com/gemmadlou/semantiq.git
EOL

## Set Origin
cd $DIR && ../

git remote set-url origin $URL

if [ -z "$RELEASE" ]; then
    echo "NO RELEASE"
    exit;
fi

echo "RELEASING"

npm version $RELEASE -m "Version $VERISON released"

git tag -a $VERSION -m "$VERSION"

git pull --rebase && git push -u origin master --follow-tags